# Generated by Django 3.2.6 on 2021-08-29 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('username', models.CharField(default='js', max_length=150, primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField(default=datetime.datetime(2021, 8, 29, 17, 35, 33, 166739))),
                ('num_followers', models.IntegerField(default=0)),
                ('repos_str', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
