# Generated by Django 3.2.6 on 2021-08-29 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('othryz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 29, 17, 36, 3, 423097)),
        ),
    ]
