# Generated by Django 3.2.6 on 2021-08-29 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('othryz', '0002_alter_userprofile_last_updated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
