# Generated by Django 3.2.6 on 2021-08-29 13:57

import datetime
import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('othryz', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=150)),
                ('repos_str', models.CharField(default='', max_length=1000)),
                ('num_followers', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(default=datetime.datetime(2021, 8, 29, 19, 27, 25, 373747))),
                ('repos', django.contrib.postgres.fields.hstore.HStoreField(default=dict)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
