# Generated by Django 3.2.6 on 2021-08-30 12:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('othryz', '0006_auto_20210829_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='name',
        ),
        migrations.AddField(
            model_name='repository',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='othryz.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 30, 18, 7, 40, 549784)),
        ),
    ]
