# Generated by Django 3.2.6 on 2021-08-30 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('othryz', '0008_auto_20210830_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 30, 18, 27, 25, 495354)),
        ),
    ]
