# Generated by Django 3.2.6 on 2021-09-08 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('othryz', '0009_auto_20210830_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='repos',
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 8, 22, 7, 47, 127988)),
        ),
    ]
